name: 'BY II Hizqiyah '
favicon: null
layout_spectrum: 0.6269
typography_spectrum: 1
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: BY II HizqiyahY
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#65635D'
    - '#BDB4A3'
    - '#FFFBBD'
    - '#B4A36E'
  brandStrength: 0.6875
  lightness: 0.03942652
  saturation: 0.5625
  rhythmicContrast: 0.6505376
purpose: []
