name: BY II Hizqiyah (Y)
favicon: null
layout_spectrum: 0.2689817559439689
typography_spectrum: 0.9431268069893122
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6196699817664921
  lightness: 0.29960945062339306
  saturation: 0.8791261399164796
  rhythmicContrast: 0.24097426910884678
purpose: []
